exclude: '*.css'

linters:

  LeadingZero:
    enabled: false

  NameFormat:
    exclude:
      # roboto variable name can't change
      - '*/typography.scss'

  TrailingSemicolonAfterPropertyValue:
    exclude:
      # Due to a weird parsing quirk
      - '*/_mixins.scss'
