language: ruby
rvm:
  - "1.9.3"
language: python
python:
  - "2.7"
  - "pypy"
env:
  - NO_FRONTEND=1
install:
  - if [[ -z "$NO_FRONTEND" ]]; then sudo add-apt-repository --yes ppa:chris-lea/node.js; fi
  - if [[ -z "$NO_FRONTEND" ]]; then sudo apt-get update -qq; fi
  - if [[ -z "$NO_FRONTEND" ]]; then sudo apt-get install nodejs; fi
  - if [[ -z "$NO_FRONTEND" ]]; then sudo npm install -g coffeelint csslint bower; fi
  - if [[ -z "$NO_FRONTEND" ]]; then gem install scss-lint; fi
  - if [[ -z "$NO_FRONTEND" ]]; then bower install; fi
  - if [[ -z "$NO_PYTHON" ]]; then export REQ_TXT=requirements/dev.txt; else export REQ_TXT=requirements.txt; fi; pip install -r "$REQ_TXT"
script:  ./run_tests.sh
matrix:
  include:
    - python: "2.7"
      env: NO_PYTHON=1
