language: python
rvm:
  - "1.9.3"
node_js:
  - "0.10"
python:
  - "2.7"
  - "pypy"
install:
  - sudo npm install -g coffeelint csslint
  - gem install scss-lint
  - pip install -r requirements-dev.txt
script:  ./run_tests.sh
