language: ruby
rvm:
  - "1.9.3"
language: python
python:
  - "2.7"
  - "pypy"
env:
  - NO_FRONTEND=1
install:
  - test -z "$NO_FRONTEND" && sudo add-apt-repository --yes ppa:chris-lea/node.js
  - test -z "$NO_FRONTEND" && sudo apt-get update -qq
  - test -z "$NO_FRONTEND" && sudo apt-get install nodejs
  - test -z "$NO_FRONTEND" && sudo npm install -g coffeelint csslint bower
  - test -z "$NO_FRONTEND" && gem install scss-lint
  - test -z "$NO_FRONTEND" && bower install
  - test -z "$NO_PYTHON" && pip install -r requirements-dev.txt
script:  ./run_tests.sh
matrix:
  include:
    - python: "2.7"
      env: NO_PYTHON=1
