language: python
python:
  - "2.7"
  - "pypy"
install:
  - sudo add-apt-repository --yes ppa:chris-lea/node.js
  - sudo apt-get update -qq
  - sudo apt-get install nodejs ruby1.9.3
  - sudo npm install -g coffeelint csslint
  - sudo gem install sass
  - pip install -r requirements-dev.txt
script:  ./run_tests.sh
